src/Entity/Employer.php
<?php

namespace App\Entity;

use App\Repository\EmployerRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EmployerRepository::class)
 */
class Employer
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_employer;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     */
    private $Poste;

    /**
     * @ORM\Column(type="string", length=255,)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telephone;

    /**
     * @ORM\Column(type="date")
     */
    private $date_ajout;

    /**
     * @ORM\OneToOne(targetEntity=Tache::class, mappedBy="nom_employer", cascade={"persist", "remove"})
     */
    private $tache;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     */
    private $prenom;

    public function __construct()
    {
        $this->date_ajout = new \DateTime('now');
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEmployer(): ?string
    {
        return $this->nom_employer;
    }

    public function setNomEmployer(string $nom_employer): self
    {
        $this->nom_employer = $nom_employer;

        return $this;
    }

    public function getPoste(): ?string
    {
        return $this->Poste;
    }

    public function setPoste(string $Poste): self
    {
        $this->Poste = $Poste;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getDateAjout(): ?\DateTimeInterface
    {
        return $this->date_ajout;
    }

    public function setDateAjout(\DateTimeInterface $date_ajout): self
    {
        $this->date_ajout = $date_ajout;

        return $this;
    }

    public function getTache(): ?Tache
    {
        return $this->tache;
    }

    public function setTache(Tache $tache): self
    {
        // set the owning side of the relation if necessary
        if ($tache->getNomEmployer() !== $this) {
            $tache->setNomEmployer($this);
        }

        $this->tache = $tache;

        return $this;
    }
    public function __toString(){
        return $this->nom_employer; // Remplacer champ par une propriété "string" de l'entité
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }
}

src/Form/EmployerType.php
<?php

namespace App\Form;

use App\Entity\Employer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmployerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_employer')
            ->add('adresse')
            ->add('telephone')
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Employer::class,
        ]);
    }
}

src/Controller/EmployerController.php
<?php

namespace App\Controller;

use App\Entity\Employer;
use App\Form\EmployerType;
use App\Repository\EmployerRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/employer")
 */
class EmployerController extends AbstractController
{
    /**
     * @Route("/", name="app_employer_index", methods={"GET"})
     */
    public function index(EmployerRepository $employerRepository): Response
    {
        return $this->render('employer/index.html.twig', [
            'employers' => $employerRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_employer_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EmployerRepository $employerRepository): Response
    {
        $employer = new Employer();
        $form = $this->createForm(EmployerType::class, $employer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $employerRepository->add($employer, true);
            $this -> addFlash('success_message', 'nouvelle employer ajouter');
            return $this->redirectToRoute('app_employer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('employer/new.html.twig', [
            'employer' => $employer,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_employer_show", methods={"GET"})
     */
    public function show(Employer $employer): Response
    {
        return $this->render('employer/show.html.twig', [
            'employer' => $employer,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_employer_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Employer $employer, EmployerRepository $employerRepository): Response
    {
        $form = $this->createForm(EmployerType::class, $employer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $employerRepository->add($employer, true);
            $this -> addFlash('success_message', 'l employer a été bien modifier');
            return $this->redirectToRoute('app_employer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('employer/edit.html.twig', [
            'employer' => $employer,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_employer_delete", methods={"POST"})
     */
    public function delete(Request $request, Employer $employer, EmployerRepository $employerRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$employer->getId(), $request->request->get('_token'))) {
            $employerRepository->remove($employer, true);
            $this -> addFlash('success_message', 'l employer a été supprimer');
        }

        return $this->redirectToRoute('app_employer_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/employer/_delete_form.html.twig
<form method="post" action="{{ path('app_employer_delete', {'id': employer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ employer.id) }}">
    <button class="btn">Delete</button>
</form>

templates/employer/_form.html.twig
{% include "layout/header.html.twig" %}
<div class="content-wrapper">
    <section class="content-header">
    <div class="container-fluid">
<div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- general form elements -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Employés</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              {{ form_start(form) }}
                <div class="card-body">
                  <div class="form-group">
                    <div class="row">
                        <div class="col-6">
                            <label for="">Nom et prenom: </label>
                            {{ form_widget(form.nom_employer) }}
                        </div>
                    </div>
                  </div>
                  <div class="form-group">
                   <div class="row">
                    <div class="col-6">
                        <label for="">Adresse: </label>
                        {{ form_widget(form.adresse) }}
                    </div>
                   </div>
                  </div>
                  <div class="form-group">
                   <div class="row">
                    <div class="col-6">
                        <label for="">telephone: </label>
                        {{ form_widget(form.telephone) }}
                    </div>
                   </div>
                  </div>
                  
                  
                  
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                   <button type="submit" class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
                
                <a href="{{ path('app_employer_index') }}"> <button type="button" class="btn btn-danger">Retour</button></a>
                </div>
            {{ form_end(form) }}
            </div>
            <!-- /.card -->

    </section>
    </div>  
 {% include "layout/footer.html.twig" %}    

templates/employer/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Employer{% endblock %}

{% block body %}

    {{ include('employer/_form.html.twig', {'button_label': 'Modifier'}) }}

    

    {{ include('employer/_delete_form.html.twig') }}
{% endblock %}

templates/employer/index.html.twig
{% include "layout/header.html.twig" %}



{% block body %}
<div class="content-wrapper">
    <section class="content-header">
    <div class="container-fluid">
    <div class="row">
              <div class="col-12">
              {% for message in app.flashes('success_message') %}
                  <div class="alert alert-success alert-dismissible fade show"> {{message}}
                  <button type="button" class="close" data-dismiss="alert" aria-label="close">
                    <span arial-hidden="true"></span>
                  </button>
              </div>
              {% endfor %}
                <div class="card">
                  <div class="card-header">
                    
                    <h3 class="card-title">Les Employers</h3>
                    
                    <div class="card-tools">
                      <div class="input-group input-group-sm" style="width: 150px;">
                            
                        <div class="input-group-append">
                        
                        </div>
                        
                               <a href="{{ path('app_employer_new') }}"><button class="btn btn-success"><i class="fas fa-user-plus"></i> </button></a>
                        
                      </div>
                      
                    </div>
                    
                  </div>
                  
                  <!-- /.card-header -->
                  <div class="card-body table-responsive p-0">
                    <table class="table table-hover text-nowrap">
                      <thead>
                        <tr>
                            <th>Id</th>
                            <th>Nom et prenom</th>
                            <th>Adresse</th>
                            <th>Telephone</th>
                            <th>Date d'ajout</th>
                            <th>actions</th>
                        </tr>
                      </thead>
                
                      <tbody>

                        {% for employer in employers %}
                        <tr>
                            <td>{{ employer.id }}</td>
                            <td>{{ employer.nomEmployer }}</td>
                            <td>{{ employer.adresse }}</td>
                            <td>{{ employer.telephone }}</td>
                            <td>{{ employer.dateAjout ? employer.dateAjout|date('Y-m-d') : '' }}</td> 
                            <td>
                              <div class="row p-0">
                                <div class="col-3">
                                <a href="{{ path('app_employer_show', {'id': employer.id}) }}"><button class="btn btn-primary"><i class="fas fa-eye"></i> </button></a>

                                </div>
                                <div class="col-3">
                                  <a href="{{ path('app_employer_edit', {'id': employer.id}) }}"><button class="btn btn-warning"><i class="fas fa-edit"></i></button></a>
                                </div>
                                <div class="col-3">
                                  <form method="post" action="{{ path('app_employer_delete', {'id': employer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ employer.id) }}">
                                    <button class="btn btn-danger"><i class="fas fa-trash"></i> </button>
                                </form>

                                {# <form method="post" action="{{ path('app_employer_delete', {'id': employer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ employer.id) }}">
                                    <button class="btn">Delete</button>
                                </form> #}
                                </div>
                              </div>                               
                                
                              </td>

                        </tr>
                        {% else %}
                        <tr>
                            <td colspan="6">no records found</td>
                        </tr>
                    {% endfor %}
                      </tbody>
                     
                    </table>
                  </div>
                  <!-- /.card-body -->
                </div>
                <!-- /.card -->
              </div>
            </div>
            </div>
 </section>
 </div>      
{% endblock %} 
{% include "layout/footer.html.twig" %} 

templates/employer/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Employer{% endblock %}

{% block body %}

    {{ include('employer/_form.html.twig') }}

{% endblock %}

templates/employer/show.html.twig
{% include "layout/header.html.twig" %}
{% block body %}
<div class="content-wrapper">
<section class="content-header">
<div class="container-fluid">
<div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Employer <b>{{ employer.nomEmployer }}</b> </h3>

                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 150px;">
                        
                    <div class="input-group-append">
                    </div>
                  </div>
                </div>
              </div>
              <div class="card-body table-responsive p-0">
                <table class="table table-hover ">
                  <thead>
                    
                    
                        <tr>
                            <td>Id</td>
                            <td>{{ employer.id }}</td>
                        </tr>
                        <tr>
                            <td>Nom_employer</td>
                            <td>{{ employer.nomEmployer }}</td>
                        </tr>
                        <tr>
                            <td>Poste</td>
                            <td>{{ employer.Poste }}</td>
                        </tr>
                        <tr>
                            <td>Adresse</td>
                            <td>{{ employer.adresse }}</td>
                        </tr>
                        <tr>
                            <td>Telephone</td>
                            <td>{{ employer.telephone }}</td>
                        </tr>
                        <tr>
                            <td>Date_ajout</td>
                            <td>{{ employer.dateAjout ? employer.dateAjout|date('Y-m-d') : '' }}</td>
                        </tr>
                    </tbody>
                  <td><a href="{{ path('app_employer_index') }}"><button  type="submit" class="btn btn-danger btn-lg">Retour</button></a>
                  <a href="{{ path('app_employer_edit', {'id': employer.id}) }}"><button  type="submit" class="btn btn-warning btn-lg">Modifier</button></a>
                  </tr>
                 
                  
                      
                    </thead>
                    
                </table>
                
              </div>
              
              
            </div>
        </div>
        </div>
</div>
</div>
 {{ include('user/_delete_form.html.twig') }}
{% endblock %}
{% include "layout/footer.html.twig" %}