src/Entity/ListeTache.php
<?php

namespace App\Entity;

use App\Repository\ListeTacheRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ListeTacheRepository::class)
 */
class ListeTache
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_tache;

    /**
     * @ORM\Column(type="date")
     */
    private $date_ajout;

    /**
     * @ORM\OneToOne(targetEntity=Tache::class, mappedBy="nom_tache", cascade={"persist", "remove"})
     */
    private $tache;
    
    public function __construct()
    {
        $this->date_ajout = new \DateTime('now');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomTache(): ?string
    {
        return $this->nom_tache;
    }

    public function setNomTache(string $nom_tache): self
    {
        $this->nom_tache = $nom_tache;

        return $this;
    }

    public function getDateAjout(): ?\DateTimeInterface
    {
        return $this->date_ajout;
    }

    public function setDateAjout(\DateTimeInterface $date_ajout): self
    {
        $this->date_ajout = $date_ajout;

        return $this;
    }

    public function getTache(): ?Tache
    {
        return $this->tache;
    }

    public function setTache(Tache $tache): self
    {
        // set the owning side of the relation if necessary
        if ($tache->getNomTache() !== $this) {
            $tache->setNomTache($this);
        }

        $this->tache = $tache;

        return $this;
    }

    public function __toString(){
        return $this->nom_tache; // Remplacer champ par une propriété "string" de l'entité
    }
}

src/Form/ListeTacheType.php
<?php

namespace App\Form;

use App\Entity\ListeTache;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ListeTacheType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_tache')
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ListeTache::class,
        ]);
    }
}

src/Controller/ListeTacheController.php
<?php

namespace App\Controller;

use App\Entity\ListeTache;
use App\Form\ListeTacheType;
use App\Repository\ListeTacheRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/liste/tache")
 */
class ListeTacheController extends AbstractController
{
    /**
     * @Route("/", name="app_liste_tache_index", methods={"GET"})
     */
    public function index(ListeTacheRepository $listeTacheRepository): Response
    {
        return $this->render('liste_tache/index.html.twig', [
            'liste_taches' => $listeTacheRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_liste_tache_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ListeTacheRepository $listeTacheRepository): Response
    {
        $listeTache = new ListeTache();
        $form = $this->createForm(ListeTacheType::class, $listeTache);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $listeTacheRepository->add($listeTache, true);
            $this -> addFlash('success_message', 'nouvelle tache ajouter');
            return $this->redirectToRoute('app_liste_tache_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('liste_tache/new.html.twig', [
            'liste_tache' => $listeTache,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_liste_tache_show", methods={"GET"})
     */
    public function show(ListeTache $listeTache): Response
    {
        return $this->render('liste_tache/show.html.twig', [
            'liste_tache' => $listeTache,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_liste_tache_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, ListeTache $listeTache, ListeTacheRepository $listeTacheRepository): Response
    {
        $form = $this->createForm(ListeTacheType::class, $listeTache);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $listeTacheRepository->add($listeTache, true);
            $this -> addFlash('success_message', 'la tache a été bien modifier');
            return $this->redirectToRoute('app_liste_tache_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('liste_tache/edit.html.twig', [
            'liste_tache' => $listeTache,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_liste_tache_delete", methods={"POST"})
     */
    public function delete(Request $request, ListeTache $listeTache, ListeTacheRepository $listeTacheRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$listeTache->getId(), $request->request->get('_token'))) {
            $listeTacheRepository->remove($listeTache, true);
            $this -> addFlash('success_message', 'la tache a été supprimer');
        }

        return $this->redirectToRoute('app_liste_tache_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/liste_tache/_form.html.twig
{% include "layout/header.html.twig" %}
<div class="content-wrapper">
    <section class="content-header">
    <div class="container-fluid">
<div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- general form elements -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Tache</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              {{ form_start(form) }}
                <div class="card-body">
                  <div class="form-group">
                    <div class="row">
                        <div class="col-6">
                            <label for="">Nom du tache: </label>
                            {{ form_widget(form.nom_tache) }}
                        </div>
                    </div>
                  </div>
                  
                  
                  
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                   <button type="submit" class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
                
                <a href="{{ path('app_liste_tache_index') }}"> <button type="button" class="btn btn-danger">Retour</button></a>
                </div>
            {{ form_end(form) }}
            </div>
            <!-- /.card -->

    </section>
    </div>
            
 {% include "layout/footer.html.twig" %}    

templates/liste_tache/edit.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    {{ include('liste_tache/_form.html.twig', {'button_label': 'Modifier'}) }}


    {{ include('liste_tache/_delete_form.html.twig') }}
{% endblock %}

templates/liste_tache/index.html.twig
{% include "layout/header.html.twig" %}



{% block body %}
<div class="content-wrapper">
    <section class="content-header">
    <div class="container-fluid">
    <div class="row">
              <div class="col-12">
              {% for message in app.flashes('success_message') %}
                  <div class="alert alert-success alert-dismissible fade show"> {{message}}
                  <button type="button" class="close" data-dismiss="alert" aria-label="close">
                    <span arial-hidden="true"></span>
                  </button>
              </div>
              {% endfor %}
                <div class="card">
                  <div class="card-header">
                    
                    <h3 class="card-title">Les Taches</h3>
                    
                    <div class="card-tools">
                      <div class="input-group input-group-sm" style="width: 150px;">
                            
                        <div class="input-group-append">
                        
                        </div>
                        
                               <a href="{{ path('app_liste_tache_new') }}"><button class="btn btn-success"><i class="fas fa-plus"></i> </button></a>
                        
                      </div>
                      
                    </div>
                    
                  </div>
                  
                  <!-- /.card-header -->
                  <div class="card-body table-responsive p-0">
                    <table class="table table-hover text-nowrap">
                      <thead>
                        <tr>
                            <th>Id</th>
                            <th>Nom du tache</th>
                            <th>Date d'ajout</th>
                            <th>actions</th>
                        </tr>
                      </thead>
                
                      <tbody>

                       {% for liste_tache in liste_taches %}
                        <tr>
                            <td>{{ liste_tache.id }}</td>
                            <td>{{ liste_tache.nomTache }}</td>
                            <td>{{ liste_tache.dateAjout ? liste_tache.dateAjout|date('Y-m-d') : '' }}</td>
                            <td>
                              <div class="row p-0">
                                <div class="col-3">
                                <a href="{{ path('app_liste_tache_show', {'id': liste_tache.id}) }}"><button class="btn btn-primary"><i class="fas fa-eye"></i> </button></a>

                                </div>
                                <div class="col-3">
                                  <a href="{{ path('app_liste_tache_edit', {'id': liste_tache.id}) }}"><button class="btn btn-warning"><i class="fas fa-edit"></i></button></a>
                                </div>
                                <div class="col-3">
                                  <form method="post" action="{{ path('app_liste_tache_delete', {'id': liste_tache.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ liste_tache.id) }}">
                                    <button class="btn btn-danger"><i class="fas fa-trash"></i> </button>
                                </form>
                                </div>
                              </div>                               
                                
                              </td>

                        </tr>
                        {% else %}
                        <tr>
                            <td colspan="6">no records found</td>
                        </tr>
                    {% endfor %}
                      </tbody>
                     
                    </table>
                  </div>
                  <!-- /.card-body -->
                </div>
                <!-- /.card -->
              </div>
            </div>
            </div>
 </section>
 </div>        
{% endblock %} 
{% include "layout/footer.html.twig" %}

templates/liste_tache/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ListeTache{% endblock %}

{% block body %}

    {{ include('liste_tache/_form.html.twig') }}

{% endblock %}

templates/liste_tache/show.html.twig
{% include "layout/header.html.twig" %}
{% block body %}
<div class="content-wrapper">
<section class="content-header">
<div class="container-fluid">
<div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Tache</b> </h3>

                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 150px;">
                        
                    <div class="input-group-append">
                    </div>
                  </div>
                </div>
              </div>
              <div class="card-body table-responsive p-0">
                <table class="table table-hover ">
                  <thead>
                    
                    
                        <tr>
                            <td>Id</td>
                            <td>{{ liste_tache.id }}</td>
                        </tr>
                        <tr>
                            <td>Nom_tache</td>
                            <td>{{ liste_tache.nomTache }}</td>
                        </tr>
                        <tr>
                            <td>Date_ajout</td>
                            <td>{{ liste_tache.dateAjout ? liste_tache.dateAjout|date('Y-m-d') : '' }}</td>
                        </tr>
                    
                  <td><a href="{{ path('app_liste_tache_index') }}"><button  type="submit" class="btn btn-danger btn-lg">Retour</button></a>
                  <a href="{{ path('app_liste_tache_edit', {'id': liste_tache.id}) }}"><button  type="submit" class="btn btn-warning btn-lg">Modifier</button></a>
                  </tr>
                 
                  
                      
                    </tdead>
                    
                </table>
                
              </div>
              
              
            </div>
        </div>
        </div>
</div>
</div>
 {{ include('user/_delete_form.html.twig') }}
{% endblock %}
{% include "layout/footer.html.twig" %}